name: Create Environment

on:
  create:
  pull_request:
    types: [opened, reopened]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  env_info:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Get Environment
    uses: ./.github/workflows/env_info.yml
    secrets: inherit

  create_env:
    name: Create Environment
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.event.ref_type == 'branch') && needs.env_info.outputs.exists == 'false'
    needs: env_info
    environment:
      name: ${{ needs.env_info.outputs.type }}

    steps:
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Fidalgo CLI Extension
        run: az extension add -s ${{ needs.env_info.outputs.fidalgo }} -y

      - name: Update Environment
        if: ${{ needs.env_info.outputs.exists == 'true' }}
        run: |
          az fidalgo admin environment deploy -g ${{ secrets.PROJECT_RESOURCE_GROUP }} --project-name ${{ secrets.PROJECT_NAME }} -n ${{ needs.env_info.outputs.name }}

      - name: Create Environment
        if: ${{ needs.env_info.outputs.exists == 'false' }}
        run: |
          az fidalgo admin environment create -g ${{ secrets.PROJECT_RESOURCE_GROUP }} --project-name ${{ secrets.PROJECT_NAME }} -n ${{ needs.env_info.outputs.name }} --environment-type ${{ needs.env_info.outputs.type }} --catalog-item-name ${{ needs.env_info.outputs.catalog_item }}
