name: Delete Environment

on:
  delete:
  pull_request:
    types: [closed]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Get Environment
    uses: ./.github/workflows/env_config.yml

  delete_env:
    name: Delete Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    needs: config
    environment:
      name: ${{ needs.config.outputs.type }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - id: msdev
        name: Get Environment
        uses: ./.github/actions/msdev
        with:
          name: ${{ needs.config.outputs.name }}
          type: ${{ needs.config.outputs.type }}

      - name: Delete Environment
        if: ${{ steps.msdev.outputs.exists == 'true' }}
        run: |
          az fidalgo admin environment delete -g ${{ steps.msdev.outputs.project_group }} --project-name ${{ steps.msdev.outputs.project_name }} -n ${{ needs.config.outputs.name }} -y
