name: Create Environment

on:
  create:
  pull_request:
    types: [opened, reopened]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    name: Get Environment
    uses: ./.github/workflows/env_config.yml

  create_env:
    name: Create Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    needs: config
    environment:
      name: ${{ needs.config.outputs.type }}
    outputs:
      tenant: ${{ steps.msdev.outputs.tenant }}
      group: ${{ steps.msdev.outputs.group }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - id: msdev
        name: Create Environment
        uses: ./.github/actions/msdev
        with:
          name: ${{ needs.config.outputs.name }}
          type: ${{ needs.config.outputs.type }}
          createIfNotExists: true

  add_link:
    name: Add Link to Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    needs: create_env
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Add Link to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const tenantId = ${{ needs.create_env.outputs.tenant }};
            const resourceId = ${{ needs.create_env.outputs.group }};

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `The source in this Pull Request has been deployed to Azure for review and can be accessed [here](https://portal.azure.com/#@${tenantId}/resource${resourceId})`,
            });
