name: Update Environment

on:
  push:
  pull_request:
    types: [synchronize]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Get Environment
    uses: ./.github/workflows/env_config.yml

  update_env:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Update Environment
    runs-on: ubuntu-latest
    needs: config
    environment:
      name: ${{ needs.config.outputs.type }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - id: msdev
        name: Ensure Environment
        uses: ./.github/actions/msdev
        with:
          name: ${{ needs.config.outputs.name }}
          type: ${{ needs.config.outputs.type }}
          createIfNotExists: true

      - name: Update Environment
        if: ${{ steps.msdev.outputs.exists == 'true' && steps.msdev.outputs.created == 'false' }}
        run: |
          az fidalgo admin environment deploy -g ${{ steps.msdev.outputs.project_group }} --project-name ${{ steps.msdev.outputs.project_name }} -n ${{ needs.config.outputs.name }}
