name: Update Environment

on:
  push:
  pull_request:
    types: [synchronize]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  env_info:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Get Environment
    uses: ./.github/workflows/env_info.yml
    secrets: inherit

  update_env:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Update Environment
    runs-on: ubuntu-latest
    needs: env_info
    environment:
      name: ${{ needs.env_info.outputs.type }}
      url: '/subscriptions/${{ needs.env_info.outputs.subscription }}/resourceGroups/${{ secrets.PROJECT_NAME }}-${{ needs.env_info.outputs.name }}'

    steps:
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Fidalgo CLI Extension
        run: az extension add -s ${{ needs.env_info.outputs.fidalgo }} -y

      - name: Update Environment
        if: ${{ needs.env_info.outputs.exists == 'true' }}
        run: |
          az fidalgo admin environment deploy -g ${{ secrets.PROJECT_RESOURCE_GROUP }} --project-name ${{ secrets.PROJECT_NAME }} -n ${{ needs.env_info.outputs.name }}

      - name: Create Environment
        if: ${{ needs.env_info.outputs.exists == 'false' }}
        run: |
          az fidalgo admin environment create -g ${{ secrets.PROJECT_RESOURCE_GROUP }} --project-name ${{ secrets.PROJECT_NAME }} -n ${{ needs.env_info.outputs.name }} --environment-type ${{ needs.env_info.outputs.type }} --catalog-item-name ${{ needs.env_info.outputs.catalog_item }}
